[
  {"key":"impl",      "name":"Implementation / Simulation",       "xpUnlock":0},
  {"key":"greedy",    "name":"Greedy",                            "xpUnlock":0},
  {"key":"binsearch", "name":"Binary Search",                     "xpUnlock":0},
  {"key":"prefix",    "name":"Prefix Sum / Two Pointer",          "xpUnlock":0},
  {"key":"sorting",   "name":"Sorting Algorithms",                "xpUnlock":0},
  {"key":"bruteforce","name":"Brute Force / Complete Search",     "xpUnlock":0},
  {"key":"recur",     "name":"Rekursi & Backtracking",            "xpUnlock":0},
  {"key":"math",      "name":"Matematika Dasar",                  "xpUnlock":0},
  {"key":"dp-basic",  "name":"DP Dasar (1D/2D/Knapsack)",        "xpUnlock":0},
  {"key":"graph-bfs", "name":"BFS / DFS",                         "xpUnlock":0},
  {"key":"number",    "name":"Number Theory (GCD/Sieve/Modular)", "xpUnlock":80},
  {"key":"combinatorics","name":"Kombinatorik & Probabilitas",    "xpUnlock":80},
  {"key":"bitmanip",  "name":"Bit Manipulation",                  "xpUnlock":100},
  {"key":"graph-sp",  "name":"Shortest Path (Dijkstra/BFS/SPFA)", "xpUnlock":120},
  {"key":"graph-tree","name":"Tree & LCA",                        "xpUnlock":200},
  {"key":"hashing",   "name":"Hashing",                           "xpUnlock":180},
  {"key":"dsu",       "name":"Disjoint Set Union (DSU)",          "xpUnlock":230},
  {"key":"mst",       "name":"Minimum Spanning Tree",             "xpUnlock":250},
  {"key":"topo",      "name":"Topological Sort / DAG",            "xpUnlock":280},
  {"key":"dp-adv",    "name":"DP Lanjut (Bitmask/Tree/Digit)",    "xpUnlock":300},
  {"key":"fenwick",   "name":"Fenwick Tree (BIT)",                "xpUnlock":300},
  {"key":"sparse",    "name":"Sparse Table / RMQ",                "xpUnlock":320},
  {"key":"segment",   "name":"Segment Tree",                      "xpUnlock":350},
  {"key":"matrix",    "name":"Matrix Exponentiation",             "xpUnlock":500},
  {"key":"scc",       "name":"SCC / Bridges / Articulation",      "xpUnlock":500},
  {"key":"matching",  "name":"Bipartite Matching",                "xpUnlock":600},
  {"key":"string",    "name":"String (Z / KMP / Aho-Corasick)",  "xpUnlock":600},
  {"key":"flow",      "name":"Max Flow / Min Cut",                "xpUnlock":700},
  {"key":"sqrt",      "name":"Sqrt Decomposition / Mo's",        "xpUnlock":750},
  {"key":"suffix",    "name":"Suffix Array / SA-IS",              "xpUnlock":800},
  {"key":"convex",    "name":"Convex Hull Trick / Li Chao",       "xpUnlock":900},
  {"key":"cdq",       "name":"CDQ / Offline Divide & Conquer DP","xpUnlock":1000},
  {"key":"geo",       "name":"Computational Geometry",            "xpUnlock":1000},
  {"key":"fft",       "name":"FFT / NTT / Polynomial",           "xpUnlock":1100},
  {"key":"treap",     "name":"Treap / Splay / Link-Cut Tree",    "xpUnlock":1200}
]
